### ISSUE TITLE
Ability to return focus to previous owner after closing menubar window

### ISSUE THREAD

**Issue by gimlids** [maxogden/menubar#120] opened 2016-05-11 01:16 UTC
Is this possible with Electron?

For example, on OS X, try clicking the Dropbox tray icon. Notice the previously focused window's title bar actually looks like it still has focus, but it will not receive keyboard events. Now close the Dropbox tray window by clicking the Dropbox tray icon -- keyboard focus immediately returns to the window that had it.

With menubar, the currently active window visually loses focus, and even after closing the menubar window by clicking the tray icon or calling `.hideWindow()`, you must still click the window that previously had focus, in order to refocus it.

I'm not sure what OS X mechanism is at play - a window type perhaps? Or [a certain way of creating a window](http://superuser.com/questions/448309/focus-previous-window-when-i-close-one-instead-of-one-of-the-same-application-in)? Or an OS X system call?

**Comment by simonhochrein** [comment] 2016-06-03 10:59
I know that on Linux and Windows minimize works,
but on Mac minimize does not help much.

**Comment by alpinparker** [comment] 2016-11-18 14:04
Same problem here. I've made the app hide when `esc` key is pressed, but I have to click on the previous window to return the focus to it. How do I automatically return focus to the previous window when the menubar is hidden?

**Comment by noahbenham** [comment] 2017-02-06 23:11
This is a duplicate of issue #153 and has been fixed with pull #154. This can be closed, @gimlids or @maxogden.

**Closed** 2019-06-03 20:15 UTC
