### ISSUE TITLE
Window Position is offset on multiple monitors

### ISSUE THREAD

**Issue by paullryan** [maxogden/menubar#63] opened 2015-09-08 17:48 UTC
The window position on multiple monitors on OS X is offset by the arrangement bounds offset in the y direction when displaying on a secondary monitor. 

To see this go to System Preferences > Displays > Arrangement and set offset your primary display like the following:
![built-in_retina_display](https://cloud.githubusercontent.com/assets/3146164/9742739/59a8e25a-561f-11e5-8063-094877b38b0a.png)

Then open your menubar application from the secondary display (will be offset down by the amount of offset of the secondary display.

**Comment by fabien-d** [comment] 2015-09-08 18:21
This is a regression from https://github.com/maxogden/menubar/pull/61. See https://github.com/maxogden/menubar/commit/924236e60b921eb41487146946fc6cdfcdfc6dde#diff-168726dbe96b3ce427e7fedce31bb0bcL86

A bug should [also] be opened with Electron.

**Comment by jenslind** [comment] 2015-09-08 19:41
Ah sorry for this.

Instead of #64 we could fix this in `electron-positioner` currently `y` is set to `0` on all tray positions.
https://github.com/jenslind/electron-positioner/blob/master/src/Positioner.js#L35
This issue should be fixed by just using `screenSize.y` instead of `0`.

**Comment by jingweno** [comment] 2015-09-09 05:33
+1 fixing this one. Now only the main monitor shows the pops up windows

**Comment by jenslind** [comment] 2015-09-09 10:00
This should have been fixed now. Just make sure you are using electron-positioner `2.0.1`.

@jingweno 
> Now only the main monitor shows the pops up windows
What version of electron are you using?

**Comment by jingweno** [comment] 2015-09-09 14:38
@jenslind:

> What version of electron are you using?

electrcon: 0.31.2, menubar: 2.2.1, electron-positioner: 2.0.0

**Comment by jenslind** [comment] 2015-09-09 14:44
Try use electron `0.30.2` or later, that should solve the issue.

**Comment by paullryan** [comment] 2015-09-09 15:42
With this fix, I am able to get the window on both monitors. I agree that the electron-positioner fix seems to be the best option as that's effectively what I did but my version was much more hacky ...

**Comment by paullryan** [comment] 2015-09-09 15:56
Updated #64 to use 2.0.1 of electron-positioner instead of my original fix. Tested as working in my OS X environment with the stated configuration.

**Comment by jenslind** [comment] 2015-09-09 19:26
@paullryan 
No need to bump the version: https://nodesource.com/blog/semver-tilde-and-caret

> ... the caret version, `^1.2.3` permits versions from `1.2.3` all the way up to, but not including, the next major version, `2.0.0`.

**Comment by paullryan** [comment] 2015-09-09 20:22
@jenslind I understand that it allows all the version in between but I would consider this a critical patch, thus a bump. However it's your projects so if you want to reject the pull just let me know and I'll delete it.

**Closed** 2015-09-12 18:23 UTC

**Comment by coolbox** [comment] 2016-09-20 07:13
Sorry to bring this up again, but i'm still having this issue. This looks like it was resolved a while back but when i open my menu bar app on a second monitor on OSX 10.11.6 the app shows at the top of the height of the primary monitor, as per the first comment in this thread.

electron: 1.4.0, menubar: 5.1.0 (electron-positioner: 3.0.0)

**Comment by coolbox** [comment] 2016-09-20 17:37
Ah it turns out i no longer need to provide a `y` option to drop the menu slightly down from the menubar. Removing my `y` option solved this for me.
